Repository cloudposse/github-action-atmos-affected-stacks, pull requests merged in 2024-08, with the labels that each got.

#44 Fix: Usage for README
  README.md
  README.yaml
Labels: documentation, no-release

#46 feat: add IAM auth support (required for stack config templating as of atmos `1.18.2`)
  .github/workflows/test-matrix-2-levels.yml
  .github/workflows/test-matrix-3-levels.yml
  .github/workflows/test-no-changes.yml
  .github/workflows/test-positive.yml
  action.yml
  tests/atmos.yaml
  tests/fixtures/atmos
Labels: minor

#48 feat: add IAM auth support (required for stack config templating as of atmos 1.86.2)
  action.yml
Labels: major
